### ISSUE TITLE
issue with instructor training completion rate script

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/feeds.carpentries.org#45] opened 2020-12-27 06:51 UTC
@maneesha see the error message below that the instructor training completion rate script is throwing. I can't reproduce locally, so I'm disabling this script from the feed for now.

https://github.com/carpentries/feeds.carpentries.org/runs/1613157921?check_suite_focus=true#step:18:121

```
python3 python/instructor_training_completion_rates.py
Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 706, in astype
    casted = self._values.astype(dtype, copy=copy)
ValueError: invalid literal for int() with base 10: '3 (badged)'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/***/***/python/instructor_training_completion_rates.py", line 60, in <module>
    ax = completion_rates.plot(kind='bar', title =plot_title, figsize=(8,5), legend=False, fontsize=12)
  File "/home/runner/.local/lib/python3.9/site-packages/pandas/plotting/_core.py", line 955, in __call__
    return plot_backend.plot(data, kind=kind, **kwargs)
  File "/home/runner/.local/lib/python3.9/site-packages/pandas/plotting/_matplotlib/__init__.py", line 61, in plot
    plot_obj.generate()
  File "/home/runner/.local/lib/python3.9/site-packages/pandas/plotting/_matplotlib/core.py", line 280, in generate
    self._make_plot()
  File "/home/runner/.local/lib/python3.9/site-packages/pandas/plotting/_matplotlib/core.py", line 1434, in _make_plot
    self.tick_pos = ax.convert_xunits(self.ax_index).astype(np.int)
  File "/home/runner/.local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 708, in astype
    raise TypeError(
TypeError: Cannot cast Index to dtype int64
make[1]: *** [Makefile:31: plots] Error 1
make: *** [Makefile:8: everything] Error 2
make[1]: Leaving directory '/home/runner/work/***/***'
```

**Comment by maneesha** [comment] 2021-01-04 19:16
I can't reproduce this either. Maybe a momentary glitch? Can we try re-enabling it and see what happens?

**Comment by fmichonneau** [comment] 2021-01-04 19:22
I only allowed the script to continue if this script failed. The error is still here: https://github.com/carpentries/feeds.carpentries.org/runs/1645511946?check_suite_focus=true#step:18:125 

it looks like the script is expecting a number but it's getting '3 (badged)'?

**Comment by maneesha** [comment] 2021-01-04 20:34
Hmm... it runs fine for me locally and it's run fine on the server to date.  The server is using a newer version of Python and pandas than what I have locally... it's possible there have been changes in how some data types are treated. I'll look into this more.

**Comment by maneesha** [comment] 2021-01-04 20:58
OK, I just tested this in a new virtual environment and I get the same error now.  Assigning to myself to fix this.

**Comment by maneesha** [comment] 2021-01-08 15:08
This had been working fine until recently.  Leaving notes for myself for future reference.
As of Python 3.9.1 and Pandas 1.2.0, something new is happening to datatypes. When a column or index has mixed data types, that column is cast as the least restrictive data type.  So `[0, 1, 2, "3 (badged)"]` should have been a object (string) data type, and it appears that is the case when the dataframe is built.  `completion_rates.dtypes` confirms this.

But then when the bar plot is created, it seems to think it's an int data type and then throws an error when it gets to the string value.

I haven't been able to figure out how/why this happens so I'm removing "badged" from the final item so all items are clearly integers.

**Closed** 2021-01-12 19:47 UTC
